export const ComponentIDs = {
  aboutUsMenuItem: 'aboutUsMenuItem',
  addBudgetRef: 'addBudgetRef',
  addBudgetSubmit: 'addBudgetSubmit',
  addBudgetType: 'addBudgetType',
  addBudgetAmount: 'addBudgetAmount',
  addExpenseAmount: 'addExpenseAmount',
  addExpensesButton: 'addExpensesButton',
  addExpenseName: 'addExpenseName',
  addExpenseSubmit: 'addExpenseSubmit',
  addExpenseType: 'addExpenseType',
  basicNavbarNav: 'basicNavbarNav',
  budgetMenuItem: 'budgetMenuItem',
  currentUserDropdown: 'currentUserDropdown',
  currentUserDropdownSignOut: 'currentUserDropdownSignOut',
  expensesMenuItem: 'expensesMenuItem',
  editBudgetLink: 'editBudgetLink',
  editExpenseLink: 'editExpenseLink',
  homeFormName: 'homeFormName',
  homeFormSubmit: 'homeFormSubmit',
  homeMenuItem: 'homeMenuItem',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  securityRef: 'securityRef',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormPIN: 'signInFormPIN',
  signInFormSubmit: 'signInFormSubmit',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormPIN: 'signUpFormPIN',
  signUpFormSubmit: 'signUpFormSubmit',
};

export const PageIDs = {
  aboutUsPage: 'aboutUsPage',
  filterPage: 'filterPage',
  homePage: 'homePage',
  landingPage: 'landingPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  securityPage: 'securityPage',
  signInPage: 'signInPage',
  signOutPage: 'signOutPage',
  signUpPage: 'signUpPage',
  expensePage: 'expensePage',
  addExpensePage: 'addExpensePage',
  editExpensePage: 'editExpensePage',
  budgetPage: 'budgetPage',
  addBudgetPage: 'addBudgetPage',
  editBudgetPage: 'editBudgetPage',
};
