export const ComponentIDs = {
  aboutUsPage: 'aboutUsPage',
  basicNavbarNav: 'basicNavbarNav',
  currentUserDropdown: 'currentUserDropdown',
  currentUserDropdownSignOut: 'currentUserDropdownSignOut',
  filterMenuItem: 'filterMenuItem',
  homeFormName: 'homeFormName',
  homeFormBio: 'homeFormBio',
  homeFormSubmit: 'homeFormSubmit',
  homeMenuItem: 'homeMenuItem',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormPIN: 'signInFormPIN',
  signInFormSubmit: 'signInFormSubmit',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormPIN: 'signUpFormPIN',
  signUpFormSubmit: 'signUpFormSubmit',
};

export const PageIDs = {
  aboutUsPage: 'aboutUsPage',
  filterPage: 'filterPage',
  homePage: 'homePage',
  landingPage: 'landingPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  signInPage: 'signInPage',
  signOutPage: 'signOutPage',
  signUpPage: 'signUpPage',
  expensePage: 'expensePage',
  addExpensePage: 'addExpensePage',
  editExpensePage: 'editExpensePage',
  budgetPage: 'budgetPage',
  addBudgetPage: 'addBudgetPage',
  editBudgetPage: 'editBudgetPage',
};
